### ISSUE TITLE
USB OTG

### ISSUE THREAD

**Issue by lambdadroid** [ia-me176c/device-asus-K013#16]

**Comment by lambdadroid** [comment]
Completed on the kernel side. Related commits: (Edit: After several days of debugging it turned out that some of these patches weren't actually necessary...)

- https://github.com/me176c-dev/me176c-acpi/commit/aff97451f4287ddcc66ab2f53d8b2a0bd3e7dd4a
- ~~https://github.com/me176c-dev/me176c-acpi/commit/98a49ad497fcf41b238236bae5334ec29ad35ff4~~
- https://github.com/me176c-dev/android_kernel_asus_me176c/commit/6d1c8eae88135952a1df2a5afcdf7b6807619d90
- https://github.com/me176c-dev/android_kernel_asus_me176c/commit/a1a5ac3c90c43fc1bfcf97206b836c3e6c96c727 (v2)
- https://github.com/me176c-dev/android_kernel_asus_me176c/commit/21c2fa63a579c1decabaf87c06f419c0afa920f5
- https://github.com/me176c-dev/android_kernel_asus_me176c/commit/72b7d06e6b546b1e7625b5a853d777840f69f88b (v3)
- ~~https://github.com/me176c-dev/android_kernel_asus_me176c/commit/8ef568c5eafe7ca5ecec7803cd25074ab908f867~~
- ~~https://github.com/me176c-dev/android_kernel_asus_me176c/commit/081c5c74e932b73508486f749b32e38430e39242~~
- https://github.com/me176c-dev/android_device_asus_me176c/commit/97b5438f8d87ebc793cbceac1d71bdf6cf4096df
- https://github.com/me176c-dev/android_device_asus_me176c/commit/f530afa906690e77f0b1516855f83955cf3959fc

Keeping this open until Android is configured to read from inserted USB flash drives.

**Comment by youling257** [comment]
write /config/usb_gadget/g1/idVendor 0x0b05
    write /config/usb_gadget/g1/idProduct 0x7770
    mkdir /config/usb_gadget/g1/strings/0x409

what is the idvendor、idproduct ？can you help me ？

android_x86:/ $ su
android_x86:/ # cat /sys/devices/pci0000:00/0000:00:16.0/device
0x0f37
android_x86:/ # cat /sys/devices/pci0000:00/0000:00:16.0/vendor
0x8086
android_x86:/ # cat /sys/devices/pci0000:00/0000:00:16.0/uevent
DRIVER=dwc3-pci
PCI_CLASS=C0380
PCI_ID=8086:0F37
PCI_SUBSYS_ID=8086:7270
PCI_SLOT_NAME=0000:00:16.0
MODALIAS=pci:v00008086d00000F37sv00008086sd00007270bc0Csc03i80
android_x86:/ #

I want to make Androidx86 otg working.

**Comment by lambdadroid** [comment]
@youling257 `idVendor` and `idProduct` identify an USB device. It defines what is displayed when you connect the device to a PC and type `lsusb`. Normally it is supposed to be unique to each device type, but it doesn't really matter for ADB etc.

`init.usb.configfs.rc` already sets these so normally you don't need to touch them.
