### ISSUE TITLE
VPN Easy not working correctly

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#26]
When I try to connect to the VPN, the status bar shows the vpn icon. But my ip address is the same, vpn is not connected.

**Comment by lambdadroid** [comment]
It's working for me now, might have been related to the fix for https://github.com/me176c-dev/device_asus_me176c/issues/28. Let me know if the issue persists with the new build I will release in a few days.

**Comment by kurtulusakyuz** [comment]
The new incoming update does not work with vpn either.

**Comment by lambdadroid** [comment]
Which app are you using? I tested with "OpenVPN for Android" and it was working fine.

**Comment by kurtulusakyuz** [comment]
VPN Easy.It uses the OpenVPN API.

**Comment by lambdadroid** [comment]
As for #29, it would be helpful if you could get logs from your device. Hard to tell what's wrong without more information.

**Comment by kurtulusakyuz** [comment]
![daz](https://user-images.githubusercontent.com/8530122/29183070-fb6f006a-7e09-11e7-9c13-df16a8c6c74d.png)
I'm getting an error. OpenVPN works but vpn easy does not work.

**Comment by lambdadroid** [comment]
You don't need to run `adb shell` before running the logcat command. Run it directly.

**Comment by lambdadroid** [comment]
Oh, assuming `Erişim engellendi` means `Permission denied` then you need to write to a file where you have write access, e.g. `adb logcat -d > %UserProfile%\Desktop\logcat.txt`. Then it should be on your desktop.

**Comment by kurtulusakyuz** [comment]
When do I have to run this command?

**Comment by lambdadroid** [comment]
Shortly after you activated the VPN and when you notice that it doesn't connect to the Internet correctly.

**Comment by kurtulusakyuz** [comment]
https://gist.github.com/kurtulus145/291cb159033f3416608035105f8dbe8a

**Comment by lambdadroid** [comment]
Hmm, everything looks correct. It *should* be working. How do you check your IP address?

**Comment by kurtulusakyuz** [comment]
My IP address looks the same as before it was connected.

**Comment by lambdadroid** [comment]
Yes, but *where* do you check your IP address? If you open https://httpbin.org/ip, does it also display your old IP?

**Comment by kurtulusakyuz** [comment]
My screen-shot applications downloaded from Google Play are failing and the screen does not display. Does Tablet have its own screen-image-capturing feature?

**Comment by lambdadroid** [comment]
Yes. Press and hold Volume Down + Power button for a few seconds then it will capture a screenshot.

**Comment by kurtulusakyuz** [comment]
![img_20170810_215745](https://user-images.githubusercontent.com/8530122/29209836-48b8ac38-7e99-11e7-82a2-9b28171a6d2e.jpg)
![img_20170810_215811](https://user-images.githubusercontent.com/8530122/29209838-48df6bfc-7e99-11e7-88d9-1dea6b23d12a.jpg)

**Comment by lambdadroid** [comment]
Huh, well I'm not sure if there is much I can do, might be a bug in the app. The log looks fine. I might test the app later but honestly without any indication in log or anything else there is not much I can do. (especially because other VPN apps are working)

**Comment by kurtulusakyuz** [comment]
Connecting to other vpn apps I downloaded from Google Play. I think the VPN Easy application has a bug.

**Comment by lambdadroid** [comment]
Sorry, I'm not sure I understand you correctly. Have you tried other VPN apps from the play store that are working correctly?

**Comment by kurtulusakyuz** [comment]
Yes.

**Comment by lambdadroid** [comment]
Hmm, in that case I'm not sure if it's worth to spend more time on this. Anyway, thanks for reporting!
