### ISSUE TITLE
Applications see the system as an emulator.

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#27]
Applications on the tablet android system looks like an emulator like BlueStacks and memu. For example, you can look at Skinbeast and BitClaim applications.

**Comment by lambdadroid** [comment]
Does the same happen on the original ASUS system, or is it recognized properly there?

**Comment by kurtulusakyuz** [comment]
In the Asus system this is not the same thing. For example, when I install BitClaim application, Asus system does not give an error.
