### ISSUE TITLE
I can not reconnect when the wifi connection is lost.

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#28]
I'm trying to reconnect when the wifi connection is disconnected. It seems connected, but there is no internet connection.

**Comment by lambdadroid** [comment]
Have you tried turning WiFi off, and then back on. Does that work?

**Comment by vaxvhbe** [comment]
I Have the same issue, I need to reboot the tablet to get wifi working again.

**Comment by Nexive** [comment]
Turning wifi off and then back on works for me.

**Comment by kurtulusakyuz** [comment]
No, it did not work. I need to restart my tablet to work.

**Comment by lambdadroid** [comment]
Confirmed, but turning wifi off and back on works for me.
