### ISSUE TITLE
Some applications on the tablet stop working.

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#29]
Some applications on the tablet stop working. This error was not in the Asus system.

**Comment by lambdadroid** [comment]
I'm sorry, but "not working" doesn't help me fix the error. Which applications are crashing?

I'll likely not be able to help you unless you can get a log from the device shortly after the error has occurred. See https://wiki.lineageos.org/logcat.html for how to capture logs.

Please don't paste the log file directly into a comment, rather paste it on https://gist.github.com/ and copy the link here.

**Comment by kurtulusakyuz** [comment]
Telegram and BitMaker

**Comment by lambdadroid** [comment]
The second part of my comment still applies, I need the log to be able to help you :)

**Comment by kurtulusakyuz** [comment]
Thanks. I looks.

**Comment by lambdadroid** [comment]
No need to close the issue, just comment here when you've got the logs. :)

**Comment by kurtulusakyuz** [comment]
Currently I have installed the tablet kitkat. When it comes to updating it, I will switch to lineage OS.

**Comment by lambdadroid** [comment]
Alright, in that case I will close the issue for now, and you just comment here once you've tested it (it's quite likely that I've already fixed it).
