### ISSUE TITLE
The wifi connection is disconnecting itself

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#32]
The wifi connection is disconnecting itself. I have to connect again.

**Comment by lambdadroid** [comment]
Maybe your connection is bad? A log would be helpful here again.

**Comment by kurtulusakyuz** [comment]
https://gist.github.com/kurtulus145/c575f0483785d32f28e27983d8df74de

**Comment by lambdadroid** [comment]
That looks normal. Even if it disconnects (but then most likely due to connection problems) it should re-connect automatically. If not, try if a restart helps.

**Comment by kurtulusakyuz** [comment]
It's not automatically reconnecting. I'm forced to connect.

**Comment by lambdadroid** [comment]
Yeah, I noticed the same but it worked after I did a restart.

**Comment by kurtulusakyuz** [comment]
I can connect after the connection is over. The wifi connection is suddenly interrupted.

**Comment by lambdadroid** [comment]
Does this just happen normally or possibly when using one of the VPN apps?

**Comment by vaxvhbe** [comment]
I have this issue and I am not use any VPN applications. I lost the connection and I force the re-connection manually.

I do not have the problem if I have a good signal.

**Comment by lambdadroid** [comment]
So is the problem that the tablet causes WiFi disconnects or does it simply not reconnect automatically?

**Comment by kurtulusakyuz** [comment]
Yes.

**Comment by lambdadroid** [comment]
Doesn't happen for me, not sure what's going wrong for you.

**Comment by kurtulusakyuz** [comment]
I use google translate translation. I do not know what you said.

**Comment by lambdadroid** [comment]
I don't have this problem on my tablet. WiFi disconnects when I'm out of range, and as soon as I go back into range it reconnects automatically. I don't know why it's not working correctly for you.

**Comment by kurtulusakyuz** [comment]
https://youtu.be/tFFlUUVFoZg

**Comment by vaxvhbe** [comment]
I have the same behavior when I download big file (for example the last release of the image, I had a dozen disconnection from wifi).

I also noticed that the download speed in wifi varies a lot (between 0 KB / s and 1 MB / s) but not in upload.

I have no problem with any other device.

**Comment by vaxvhbe** [comment]
Logcat when I'm disconnected: https://gist.github.com/taenadil/0d2a5ed1e1fd7a7cff45feabbcec0721

**Comment by lambdadroid** [comment]
Hmm, I just downloaded the latest update with not a single disconnect... (I haven't had a single disconnect in the whole time I've been testing the ROM). Unfortunately the logs don't give any information why it disconnects, just that something causes the connection to disconnect (it could be also your router)...

**Comment by lambdadroid** [comment]
I managed to reproduce the problem that WiFi isn't reconnecting automatically (not sure how, but it just happened to me as well). I'm investigating that problem but I still have no clue why you get disconnected so frequently.

**Comment by kurtulusakyuz** [comment]
In the Asus system, the connection never broke.

**Comment by lambdadroid** [comment]
Unfortunately, that doesn't mean anything because this is now a completely different driver with barely any relation to the one used on the ASUS system.

**Comment by Minecrell** [comment]
Please go to `Settings -> Developer options` and then`Enable Wi-FI Verbose Logging` (under `Networking`). Paste your logcat here when you get disconnects again.

**Comment by lambdadroid** [comment]
I've identified and fixed the WiFi reconnects, however I'm still unsure about the cause of the WiFi disconnects (might be related?). It would be helpful if someone could volunteer to manually copy the files I've provided below and report if:

- WiFi still disconnects frequently
- WiFi still doesn't reconnect automatically

All you need to make the changes is ADB. 

1. Go into `Developer Settings` and make sure `Root access` is allowed for `ADB` (this is independent from regular rooting so make sure it's really enabled).

2. Use the following adb commands. Make sure to always check your device for the additional verification dialog and confirm if it pops up.

    ```
    adb root
    adb remount
    ```

3. Switch to the unpacked folder (it should have a `boot.img` file and a `modules` folder) and do:

    ```
    adb push boot.img /sdcard/
    adb push modules /system/lib/
    adb shell dd if=/sdcard/boot.img of=/dev/block/by-name/boot
    ```

4. Restart the device and report the results :). Let me know if one of the commands isn't working. 

Here's the download: [wifi-reconnect-fix.zip](https://github.com/me176c-dev/device_asus_me176c/files/1220487/wifi-reconnect-fix.zip)

**Comment by kurtulusakyuz** [comment]
I downloaded a file of about 1 GB. There has never been a disconnect.

**Comment by lambdadroid** [comment]
@kurtulus145 With the new files? Please test it for a day or two. If there are no disconnects anymore I will release this in the next days.

**Comment by vaxvhbe** [comment]
I have flashed your fix and I have no more disconnection at the moment. ^^

**Comment by lambdadroid** [comment]
So far nobody has reported any connection problems with the fix. I assume it is fixed?

**Comment by vaxvhbe** [comment]
It's ok for me 😁

**Comment by kurtulusakyuz** [comment]
Wifi connection never disconnect.
