### ISSUE TITLE
MTP/PTP

### ISSUE THREAD

**Issue by lambdadroid** [ia-me176c/device-asus-K013#33]
Listing files is sometimes possible, but fetching or sending files is not working correctly.

It seems like this might be an issue in the USB kernel driver that was fixed in a newer kernel version. However, due to the number of patches required I don't think it's worth backporting all of these so we'll have to wait until we can do a kernel upgrade.

**Comment by lambdadroid** [comment]
MTP/PTP are now completely broken due to the kernel upgrade to 4.14. The required changes are in Oreo, but too much to backport. I'll delay this until Oreo.

Until then, ADB can be used to transfer files (and personally I think this is the better option anyway; MTP sucks...)

**Comment by youling257** [comment]
How to use adb ? android-4.14 no adb function，
ANDROID: usb: gadget: adb: Add ADB function，ANDROID: usb: gadget: mtp: Add MTP/PTP function，
android-4.14 no these patches.

**Comment by youling257** [comment]
[ 1472.889801] rndis_register: configNr = 0
[ 1472.889862] udc dwc3.3.auto: registering UDC driver [g1]
[ 1472.889900] configfs-gadget gadget: adding 'rndis'/00000000eaae0b2b to config 'b'/00000000067f287d
[ 1472.891223] rndis_set_param_medium: 0 0
[ 1472.891228] configfs-gadget gadget: RNDIS: super speed IN/ep1in OUT/ep1out NOTIFY/ep2in
[ 1472.990194] configfs-gadget gadget: suspend


[ 1492.572875] udc dwc3.3.auto: registering UDC driver [g1]
[ 1492.572899] configfs-gadget gadget: adding 'gmidi function'/000000005b7657c1 to config 'b'/00000000067f287d
[ 1492.575218] configfs-gadget gadget: f_midi_register_card() finished ok
[ 1492.673783] configfs-gadget gadget: suspend
[ 1500.691928] configfs-gadget dwc3.3.auto: unregistering UDC driver [g1]
[ 1500.692056] configfs-gadget gadget: unbind function 'gmidi function'/000000005b7657c1
[ 1500.692059] configfs-gadget gadget: unbind
[ 1500.692061] configfs-gadget gadget: disable
[ 1500.692404] android_work: did not send uevent (0 0           (null))

[ 4411.499188] udc dwc3.3.auto: registering UDC driver [g1]
[ 4411.499223] configfs-gadget gadget: adding 'audio_source'/00000000f0aeff93 to config 'b'/00000000067f287d

[ 1518.120823] udc dwc3.3.auto: registering UDC driver [g1]
[ 1518.120858] configfs-gadget gadget: adding 'Function FS Gadget'/00000000d194e4ab to config 'b'/00000000067f287d
[ 1518.120862] ffs_do_functionfs_bind()
[ 1518.120867] configfs-gadget gadget: adding 'Function FS Gadget'/00000000d194e4ab --> -19
[ 1518.120881] configfs-gadget dwc3.3.auto: failed to start g1: -19
[ 1518.120918] init: write_file: Unable to write to '/config/usb_gadget/g1/UDC': No such device

**Comment by youling257** [comment]
gadget legacy drivers，modprobe g_mass_storage file=/dev/block/mmcblk2p4

[ 3468.740287] udc dwc3.3.auto: registering UDC driver [g_mass_storage]
[ 3468.740311] Mass Storage Function, version: 2009/09/11
[ 3468.740321] LUN: removable file: (no medium)
[ 3468.740459] lun0: open backing file: /dev/block/mmcblk2p4
[ 3468.740463] LUN: file: /dev/block/mmcblk2p4
[ 3468.740468] Number of LUNs=1
[ 3468.740476] g_mass_storage gadget: adding config #1 'Linux File-Backed Storage'/000000002e15e245
[ 3468.740481] g_mass_storage gadget: adding 'Mass Storage Function'/00000000e9e09a80 to config 'Linux File-Backed Storage'/000000002e15e245
[ 3468.740590] g_mass_storage gadget: I/O thread pid: 16551
[ 3468.740605] g_mass_storage gadget: cfg 1/000000002e15e245 speeds: super high full
[ 3468.740608] g_mass_storage gadget:   interface 0 = Mass Storage Function/00000000e9e09a80
[ 3468.740614] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[ 3468.740620] g_mass_storage gadget: userspace failed to provide iSerialNumber
[ 3468.740624] g_mass_storage gadget: g_mass_storage ready
[ 3468.838513] g_mass_storage gadget: suspend

**Comment by youling257** [comment]
mtp/ptp: Switch to FunctionFS userspace interface
https://android.googlesource.com/device/google/wahoo/+/android-8.1.0_r33/init.hardware.usb.rc
https://android.googlesource.com/device/linaro/hikey/+/master/init.common.usb.rc
https://android.googlesource.com/device/linaro/hikey/+/678d29f18f5bbf1f3fad89bda02d657eed6c8692

Test: Tested manual MTP/PTP transfers on android-hikey-linaro-{4.4,4.9}
      and 4.14-rcX kernels with and without USB_CONFIGFS_F_{MTP,PTP}
      drivers enabled.

**Comment by lambdadroid** [comment]
@youling257 You need to configure configfs properly to use ADB.

Mostly this just means:
- Create a basic gadget configuration: https://github.com/me176c-dev/android_device_asus_me176c/blob/cm-14.1/init/root/init.me176c.common.rc#L14-L22
- Make sure you set `manufacturer`, `product` and `serialnumber`: https://github.com/me176c-dev/android_device_asus_me176c/blob/cm-14.1/init/root/init.me176c.common.rc#L35-L37
- Set `sys.usb.configfs` to `1` to `boot` (not earlier or it won't work): https://github.com/me176c-dev/android_device_asus_me176c/blob/cm-14.1/init/root/init.me176c.common.rc#L39-L40
