### ISSUE TITLE
Add signature faking support

### ISSUE THREAD

**Issue by jerbmega** [ia-me176c/device-asus-K013#41]
Signature faking will allow for applications like MicroG to work without needing to mess with Xposed or Magisk.

Here's a patch maintained by the MicroG team: https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-N.patch

**Comment by lambdadroid** [comment]
Done in https://github.com/me176c-dev/frameworks_base/commit/b2f449fe42fb3d9fb7d3c35dcec352f7a06ba4f3 and https://github.com/me176c-dev/frameworks_base/commit/e15df5ad6b86def75075e413e66071a90b216c07

**Comment by lambdadroid** [comment]
I removed the patches from the repo itself, but these patches will be manually applied before each release (just like the Substratum patches). I want to avoid adding patches to the repos that are not strictly required for compatibility with the tablet.
