### ISSUE TITLE
Weird beep sounds when using touch sounds

### ISSUE THREAD

**Issue by lambdadroid** [ia-me176c/device-asus-K013#5]
Sometimes, touch sounds are not played correctly and will result in some kind of beep played on the device. The following touch sounds after that will work correctly again. A simple workaround is to disable touch sounds.

**Comment by lambdadroid** [comment]
Haven't heard them anymore for a while.

**Comment by youling257** [comment]
beep played ? if i understand right，the headphone sometimes will beep played，speaker no this problem.

08-25 06:16:11.647  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:12.007  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:12.368  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:12.727  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:13.087  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:13.106  3599  3668 W AudioFlinger: write blocked for 328 msecs, 171 delayed writes, thread 0xb6118100
08-25 06:16:13.447  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:13.807  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:14.167  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:14.527  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:14.887  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:15.247  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:15.607  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:15.967  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:16.327  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:16.687  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:17.046  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:17.407  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:17.767  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:18.127  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:18.145  3599  3668 W AudioFlinger: write blocked for 329 msecs, 185 delayed writes, thread 0xb6118100
08-25 06:16:18.487  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:18.848  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:19.208  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:19.567  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:19.927  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:19.958  3939  4377 W VibratorService: Tried to stop vibrating but there is no vibrator device.
08-25 06:16:19.960  3939  4377 W VibratorService: Tried to vibrate but there is no vibrator device.
08-25 06:16:20.010  3939  3939 W VibratorService: Tried to stop vibrating but there is no vibrator device.
08-25 06:16:20.287  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:20.647  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:16:22.027  3939 11094 W VibratorService: Tried to stop vibrating but there is no vibrator device.
08-25 06:16:22.027  3939 11094 W VibratorService: Tried to vibrate but there is no vibrator device.
08-25 06:16:22.078  3939  3939 W VibratorService: Tried to stop vibrating but there is no vibrator device.
08-25 06:16:23.676  7884 11660 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-25 06:16:24.853  3939  4377 W VibratorService: Tried to stop vibrating but there is no vibrator device.
08-25 06:16:24.853  3939  4377 W VibratorService: Tried to vibrate but there is no vibrator device.
08-25 06:16:24.902  3939  3939 W VibratorService: Tried to stop vibrating but there is no vibrator device.

**Comment by youling257** [comment]
08-25 06:10:08.703  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:10:09.063  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:10:09.098  3939  4063 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz
08-25 06:10:09.423  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:10:09.603  3939  4063 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz
08-25 06:10:09.783  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:10:10.143  3599  3667 W audio_hw_primary: out_write underrun: -32
08-25 06:10:10.457  3939  4063 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz
08-25 06:10:10.503  3599  3667 W audio_hw_primary: out_write underrun: -32

**Comment by lambdadroid** [comment]
@youling257 I don't have this problem anymore. I should note that I'm using a different Audio HAL as Android x86 though, so it's a bit different.

**Comment by youling257** [comment]
I don't have it “AudioFlinger: mixer(0xf5c03680) throttle end: throttle time(10)”anymore on Androidx86
