### ISSUE TITLE
Offline Mode Charging crashes immediately

### ISSUE THREAD

**Issue by lambdadroid** [ia-me176c/device-asus-K013#56]
When booting with the charger connected, the offline mode UI is never shown. Instead, the screen turns black so it looks like the tablet turns off, even though it is still turned on. It can only be stopped by pressing the power button for ~10 seconds or disconnecting the battery.

Probably need to port the patches from cm-14.1: https://github.com/me176c-dev/android_bootable_recovery/commits/cm-14.1

**Comment by Alex-from-the-90s** [comment]
Just viewed the root filesystem of my MemoPad and saw file fstab.charger.me176c with the following content:
```
dev/block/by-name/system	/system	ext4	ro,noatime	wait
*/block/sd*              	/Removable/USBdisk1	vfat	None	wait,noemulatedsd,voldmanaged=USBdisk1:auto
*/block/sd*              	/Removable/USBdisk2	vfat	None	wait,noemulatedsd,voldmanaged=USBdisk2:auto
*/block/mmcblk1*         	/Removable/MicroSD	vfat	None	wait,noemulatedsd,voldmanaged=MicroSD:auto
```
Can this help? Maybe filesystem initializes itself in a different way when device charging?

**Comment by lambdadroid** [comment]
> Just viewed the root filesystem of my MemoPad and saw file fstab.charger.me176c with the following content:
> 
> ```
> dev/block/by-name/system	/system	ext4	ro,noatime	wait
> */block/sd*              	/Removable/USBdisk1	vfat	None	wait,noemulatedsd,voldmanaged=USBdisk1:auto
> */block/sd*              	/Removable/USBdisk2	vfat	None	wait,noemulatedsd,voldmanaged=USBdisk2:auto
> */block/mmcblk1*         	/Removable/MicroSD	vfat	None	wait,noemulatedsd,voldmanaged=MicroSD:auto
> ```
> 
> Can this help? Maybe filesystem initializes itself in a different way when device charging?

Thanks, but it turned out only two small fixes were needed in `bootable/recovery` to make this work properly.
