### ISSUE TITLE
SetupWizard crashes when Google Apps are installed

### ISSUE THREAD

**Issue by RandomTypek** [ia-me176c/device-asus-K013#57]
There seems to be a crash right after connecting to WiFi, with a message "Settings app keeps force closing". The setup still somehow recovers after that, I'm able to finish it anyways by going back to the beginning and starting again, so I guess it's not a huge issue but still. Note that this also happened on previous LineageOS 16 builds. Tested only with x86 nano OpenGApps for Android 9.

Here's a part of the logcat which seems to be relevant (full logcat is attached as well, just in case):

02-02 11:33:42.708  1331  1331 E AndroidRuntime: FATAL EXCEPTION: main
02-02 11:33:42.708  1331  1331 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 1331
02-02 11:33:42.708  1331  1331 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.google.android.setupwizard/com.google.android.setupwizard.network.CaptivePortal}: java.lang.IllegalStateException: Finish requested twice
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3172)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3179)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Finish requested twice
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.google.android.setupwizard.util.NoJankFinishFragment.finishAction(NoJankFinishFragment.java:120)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressActivity.onFragmentResult(ProgressActivity.java:233)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressFragment.sendFragmentResult(ProgressFragment.java:113)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressFragment.sendFragmentResult(ProgressFragment.java:100)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at com.google.android.setupwizard.network.NetworkCheckFragment.onActivityCreated(NetworkCheckFragment.java:38)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.Fragment.performActivityCreated(Fragment.java:2531)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:406)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7284)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
02-02 11:33:42.708  1331  1331 E AndroidRuntime: 	... 12 more
02-02 11:33:42.723   367  2397 W ActivityManager:   Force finishing activity com.google.android.setupwizard/.network.CaptivePortal
02-02 11:33:42.796   367  1550 I WindowManager: WIN DEATH: Window{8d41979 u0 com.google.android.setupwizard/com.google.android.setupwizard.network.CaptivePortal}
02-02 11:33:42.797   367  1139 I ActivityManager: Process com.google.android.setupwizard (pid 1331) has died: fore TOP 
02-02 11:33:42.800   367   367 V NotificationListeners: notification listener connection lost: ComponentInfo{com.google.android.setupwizard/com.google.android.setupwizard.predeferred.NotificationConsolidatorService}
02-02 11:33:42.800   367  2886 I StatusBarManagerService: binder died for pkg=null
02-02 11:33:42.801   367  1606 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=8, [ Transports: WIFI Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN Unwanted:  Uid: 10026] ], android.os.BinderProxy@b422eb0)
02-02 11:33:42.801   367  1301 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=7, [ Transports: WIFI Capabilities: NOT_VPN Unwanted:  Uid: 10026] ], android.os.BinderProxy@187b129)
02-02 11:33:42.814   367  1139 W ActivityManager: Scheduling restart of crashed service com.google.android.setupwizard/.predeferred.NotificationConsolidatorService in 1000ms
02-02 11:33:42.815   367  1353 D NotificationListeners: Removing active service ComponentInfo{com.google.android.setupwizard/com.google.android.setupwizard.predeferred.NotificationConsolidatorService}
02-02 11:33:42.817   367  1067 W WifiService: Client connection lost with reason: 4
02-02 11:33:42.828   367  1637 I WindowManager: WIN DEATH: Window{7567bef u0 com.google.android.setupwizard/com.google.android.setupwizard.network.NetworkActivity}
02-02 11:33:42.835   367  1641 I WindowManager: WIN DEATH: Window{6abbd43 u0 com.google.android.setupwizard/com.google.android.setupwizard.user.WelcomeActivity}
02-02 11:33:42.839   367   379 I WindowManager: WIN DEATH: Window{a9c3e5b u0 com.google.android.setupwizard/com.google.android.setupwizard.network.WifiActivity}
02-02 11:33:42.913   367   392 W ActivityManager: setHasOverlayUi called on unknown pid: 1331

[logcat.txt](https://github.com/me176c-dev/android_device_asus_K013/files/2824365/logcat.txt)

**Comment by lambdadroid** [comment]
Confirmed. However, it's not clear if this is an issue in the ROM or in the Google packages. The exception happens within the Google SetupWizard:

```
02-02 19:03:28.869  1303  1303 E AndroidRuntime: FATAL EXCEPTION: main
02-02 19:03:28.869  1303  1303 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 1303
02-02 19:03:28.869  1303  1303 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.google.android.setupwizard/com.google.android.setupwizard.network.GmsCheckin}: java.lang.IllegalStateException: Finish requested twice
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3172)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3179)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Finish requested twice
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.google.android.setupwizard.util.NoJankFinishFragment.finishAction(NoJankFinishFragment.java:120)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressActivity.onFragmentResult(ProgressActivity.java:233)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressFragment.sendFragmentResult(ProgressFragment.java:113)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.google.android.setupwizard.ProgressFragment.sendFragmentResult(ProgressFragment.java:100)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at com.google.android.setupwizard.network.NetworkCheckFragment.onActivityCreated(NetworkCheckFragment.java:38)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.Fragment.performActivityCreated(Fragment.java:2531)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:406)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7284)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
02-02 19:03:28.869  1303  1303 E AndroidRuntime: 	... 12 more
```

The Google Apps are proprietary, and third party (not part of the ROM), so I'm not sure what I can do here. However, let's keep the issue open in case others run into the same issue or want to take a closer look.

It seems to configure just fine after the crash (I did not even have to re-enter the WiFi password), so it's really not a big deal for now.

**Comment by lambdadroid** [comment]
Does not seem to happen anymore on new builds. Yay!
