### ISSUE TITLE
latest (3.3.1) TWRP doesn't seem to work on the 8Gb version of the memopad

### ISSUE THREAD

**Issue by empty-fortress** [ia-me176c/device-asus-K013#67]
the latest (3.3.1) TWRP for me176c version doesn't seem to work on the 8Gb version of the memotab I have, but 3.2.1 does. 3.3.1 runs fine on the 16Gb model. I haven't tested other versions yet. To be more specific, the tablet has the new bootloader, flashed correctly (I've been able to run postmarketOS on it without a problem), but booting into recovery with 3.3.1 installed just give an error screen (which just says "error").

It may be a problem with the tablet (it's second hand, half the screen doesn't respond to touch, and both cameras don't work with the stock 5.0 asus android rom). Feel free to ask if you need me to test things on it, that's exactly what I got it for.

**Comment by stephan-gh** [comment]
Can you take a picture of the error screen? It doesn't really make sense. The "ERROR" screen comes from the stock recovery. TWRP does not have such a screen, in theory.

>  and both cameras don't work with the stock 5.0 asus android rom)

Well, this is certainly not an issue for anything except the stock RAM :D (Camera doesn't work anyway)

**Comment by Alex-from-the-90s** [comment]
> the latest (3.3.1) TWRP for me176c version doesn't seem to work on the 8Gb version of the memotab I have, but 3.2.1 does. 3.3.1 runs fine on the 16Gb model. I haven't tested other versions yet. To be more specific, the tablet has the new bootloader, flashed correctly (I've been able to run postmarketOS on it without a problem), but booting into recovery with 3.3.1 installed just give an error screen (which just says "error").
> 
> It may be a problem with the tablet (it's second hand, half the screen doesn't respond to touch, and both cameras don't work with the stock 5.0 asus android rom). Feel free to ask if you need me to test things on it, that's exactly what I got it for.



> doesn't seem to work on the 8Gb version

I have model ME176CX 8 Gb and remember running TWRP and Lineage without any problems, but then I rolled back to TWRP 3.2 because it was better compatible with the stock firmware I returned to. The cameras work perfectly in the combination of my modified stock firmware with TWRP 3.2 and the bootloader 0.2.

**Comment by Alex-from-the-90s** [comment]
If I'm not mistaken ME176CX and ME176C are almost no different.

**Comment by empty-fortress** [comment]
Of course I flashed 3.3.1 over 3.2.1 and now it seems to work. I can't give you a photo but it looked like this one: https://forums.androidcentral.com/attachments/android-5-0-lollipop/177552d1432238176t-i-got-error-trying-update-5-1-1-what-can-i-do-36809.jpg (same unhelpful message, same image)

**Comment by stephan-gh** [comment]
Yeah, this comes from the stock recovery. Which shouldn't be displayed if you just flashed TWRP.
Anyway, if it's now working everything is fine I guess ¯\\\_(ツ)_/¯
